name: Build_Container
on:
  push:
    branches:
      - master
    paths:
      - 'weather-app-dockerfile'
      - 'Makefile'
      - '.github/workflows/build_cont'
jobs:


  build_container:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }} 
      IMAGE_NAME : "weather-app-pimentel"
      REGION : "ap-southeast-2"
      REPO_NAME : "julio-pimentel-node-weather-app"

    steps:
    - uses: actions/checkout@v2
    - name: Build_Container
      run: make push_docker_image